### ISSUE TITLE
Kernel is always in debug mode

### ISSUE THREAD

**Issue by tampe125** [Codeception/AspectMock#30]
In `\AspectMock\Kernel::init()` the option `debug` is always set to true.
Looking at the code, this means that the cache is never read (but it is generated). I commented it out in my local copy, however I was wondering if there is any special reason for this setting

**Comment by lionsoftware** [comment]
Please apply following patch for src/AspectMock/Kernel.php, because last commit b1e31c3fcf9 breaks fix in commit fd6453339 and same issue available in the version 3.0.x:

--- src/AspectMock/Kernel.php.orig	2019-10-14 03:02:25.000000000 +0800
+++ src/AspectMock/Kernel.php	2019-10-14 03:02:31.000000000 +0800
@@ -20,7 +20,7 @@
         if (!isset($options['excludePaths'])) {
             $options['excludePaths'] = [];
         }
-        $options['debug'] = true;
+        if (!isset($options['debug'])) $options['debug'] = true;
         $options['excludePaths'][] = __DIR__;
 
         parent::init($options);
