### ISSUE TITLE
Fail to load classes in shutdown function?

### ISSUE THREAD

**Issue by kenjis** [Codeception/AspectMock#31]
I'm not sure this is a bug of AspectMock/Go AOP, or PHP. And it happens on CentOS 6.5 (64bit). Not on Ubuntu 12.04 (32bit), Mac OS X.

I get a strange error that autoloader can't load a class when it is called in a function registered by register_shutdown_function().

I investigated it. I put the code below in shutdown function.

``` php
echo file_get_contents('php://filter/read=go.source.transforming.loader/resource=/path/to/class/file.php');
```

But nothing was outputed.

I put the same code in a test method. It worked fine.

Does anyone have any advices?

**Comment by daniel-sc** [comment]
Hi @kenjis, @lisachenko 

I encountered the same problem! Contrary to your findings above, I think this is related to GoAOP, because if I don't register the kernel, everything runs fine.

Can someone look into this?

The follwoing example reproduces the issue:

```php
<?php

use Go\Core\AspectContainer;
use Go\Core\AspectKernel;

require_once __DIR__ . '/../../vendor/autoload.php';

class MyAspectKernel extends AspectKernel
{
    protected function configureAop(AspectContainer $container)
    {
    }
}

// comment out the following line to get a positive result:
MyAspectKernel::getInstance()->init([
    'debug' => false,
    'includePaths' => [__DIR__]
]);

register_shutdown_function(function () {
    echo "shutdown function..\n";
    $mailer = new PHPMailer(); // required via composer autoload
    echo "done.\n";
});

exit;
```

Output:
```
exiting..
shutdown function..
PHP Fatal error:  Class 'PHPMailer' not found in /[PATH]/test-shutdown.php on line 23
```

System environment:
SMP Debian 3.16.7-ckt9-3~deb8u1~bpo70+1 (2015-04-27) x86_64 GNU/Linux
PHP 5.4.39-0+deb7u2 (cli) (built: Mar 25 2015 08:33:29)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
(Everything is fine on windows..)

**Comment by lisachenko** [comment]
@daniel-sc Thank you for reporting about issue, I'll try to reproduce it.

Could you retest on another PHP version, for example, 5.5 or even better, 5.6? This can be an issue in the PHP engine, so I want to give you an advice: not to perform any class-loading, file requirement, etc in the shutdown function, because engine tries to free all resources at this moment and hell knows what can be broken at this moment, probably, your callback is called after a fatal error...

Here is one case when functions are not available after loading them in the shutdown callback: https://bugs.php.net/bug.php?id=68596

**Comment by daniel-sc** [comment]
@lisachenko I can reproduce this with 5.5 and 5.6. If it helps, I can try to provide a repository with Dockerfiles to reproduce?

**Comment by daniel-sc** [comment]
@lisachenko I created a gist for reproducing the error: 
https://gist.github.com/daniel-sc/2dc6f04dc605c14c2308
Let me know if you have problems reproducing it!

**Comment by msdm** [comment]
I encountered this problem today. This autoload error only happens for "included paths" during kernel initialization. The problem is that original class loaders get unregistered in `AopComposerLoader::init()` and replaced by custom loaders. For some reason, the custom loaders don't work correctly in the shutdown phase (e.g. in the functions registered by `register_shutdown_function`). My dirty solution is to define a static function in the `AopComposerLoader` for manually re-registering original loaders in our shutdown callback function before anything else.
