### ISSUE TITLE
Phalcon PHP Mocking

### ISSUE THREAD

**Issue by jymboche** [Codeception/AspectMock#56]
Is it possible to mock a static method from the phalcon extension?

``` php
        $model = test::double("Common\\Models\\User", ["findFirst"=>new User()]);
        $user = User::findFirst();
        $model->verifyInvoked("findFirst");
```

I have a model method User::findFirst() I'm trying to mock.  User extends Phalcon\Mvc\Model (an extension class) and findFirst is a static method of that parent class. Unfortunately, verifyInvoked() returns false.   Is it possible (now OR in the future) that AspectMock could do this? Adding the findFirst method to my User model works, so it appears it is setup correctly.

**Comment by lisachenko** [comment]
Hello, from what I see, there is a small chance to make this work with Phalcon. In the order to do it, you need to implement listener for class loader component of Phalcon first.

This should be one from (not sure which is suited more):
loader:beforeCheckClass
loader:pathFound
loader:beforeCheckPath
loader:afterCheckClass 

In the listener we should have a path to the file and class name, then just give a control to the Go! AOP engine by using `FilterInjectorTransformer::rewrite($resolvedPath)`. Framework then should see this static method and mock it.

Unfortuantely, for 1.0.0 version, internal methods from extensions won't be processed, because of some weird issues with scope rebinding. I'll try to fix them later for 1.1.0 version of goaop engine.

**Comment by thiagolcks** [comment]
Hi,

I'm trying to mock a simple class that calls a static method with Phalcon and it's also not working. I'm using Phalcon 2.0.7.

````
$client = new \stdClass();
$client->email = 'joe@doe.com';

$mailer = test::double('Mailer', ['send' => null]);
$clientEmails = new \ClientEmails();
$clientEmails->sendOwnerNotification($client);

$mailer->verifyInvoked('send');
````

I tried it without PhalconPHP and it worked fine, so I think the problem is with Phalcon Loader. In my bootstrap.php I have:
````
// Required for phalcon/incubator
include __DIR__ . "/../vendor/autoload.php";

$kernel = \AspectMock\Kernel::getInstance();
$kernel->init([
    'debug' => true,
    'includePaths' => [__DIR__ . '/../app/']
]);
$kernel->loadFile('PhalconLoader.php');
````

And on the PhalconLoader.php I have:
````
$loader = new \Phalcon\Loader();
$loader->registerDirs(
    array(
        ROOT_PATH,
        PATH_LIBRARY,
        PATH_SERVICES,
    )
);
$loader->register();
````

Ideas?

**Comment by jymboche** [comment]
Not sure if this helps... but one thing I noticed is that if your class extends a phalcon class (ie: User extends Model) the phalcon methods (maybe just static methods?) it wouldnt mock them. For instance User::find() or save() wouldnt be mocked. However if in the User class I implemented my own save method, just a stub really, and called parent::save()  then mocking would work.  Kind of a pain though....

**Comment by jymboche** [comment]
@lisachenko 
Any changes in the last year that would make this possible (mocking classes/methods of the phalcon extension)? I can work on this if I knew where to start....

**Comment by sergeyklay** [comment]
@jymboche :+1:

**Comment by casank25** [comment]
@lisachenko 
Goaop is amazing and life savior. I've used it with Laravel and Symfony and it was just pleasure working with it .. Now, i have to work with Phalcon and have the same issues as guys above. It would be nice if you could give us updates on this issue or at least a timeframe. I guess more and more people are in need of that fix. Let us know please.

**Comment by jymboche** [comment]
So, just to keep the conversation going....
It seems there are 2 options from my experience:
*1. Not possible to mock phalcon extended classes*
If \Models\User extends \Phalcon\Mvc\Model the parent class methods like save() find(), etc... cannot be mocked.

*2. Phalcon Class cannot be directly mocked*
If you have a service that uses \Phalcon\Mvc\View, you cant mock this with test::double(). This is less of an issue for me. I use the codeception/phpunit $this->getMock('Phalcon\Mvc\View'); and inject the mock object into my service class. Alternatively, you could create stubs\interfaces and include them in your test autoloader.

The first issue drives me nuts though, because i have to add these proxy methods in my production code... ie:
```php
    public function save($data = null, $whitelist = null)
    {
        return parent::save($data, $whitelist);
    }
```

Im not that familiar with go aop or aspectmock but it sounds like it finds your class file, and patches the class and the autoloader? So if it cant find the parent class file \Phalcon\Mvc\Model, it doesnt know the available methods for mocking?

I was wondering if the PhalconStubs could be of use here? If you dont know, the phalcon stubs are generated php code that your ide can use for autocompletion etc... The generator is here:
https://github.com/phalcon/phalcon-devtools/blob/master/ide/gen-stubs.php

Its using php reflection to get the classes and method signatures.... I was wondering if it might be possible to do something similar and inject these stubs or proxies into the patched classes aspectmock or goaop.

Thoughts?

**Comment by lisachenko** [comment]
Hello, guys! Sorry for the late response, was too busy...

1. _Not possible to mock phalcon extended classes_
Yes, this limitation is present for 1.x tags and branch, because of usage of PHP-Token-Reflection. I can't write a code that will work with both classes transparently, so I decided to skip internal methods, because all typical applications don't need this. Phalcon is a special case, so I can understand your feeling.

However things are much better in 2.x versions (aka master), because I developed my own `goaop/parser-reflection` package that is fully compatible with internal Reflection API. This means that master branch of `goaop/framework` is able to intercept even internal methods from parent class, if your class extends an internal one.

2. _Phalcon Class cannot be directly mocked_
This is true ( Because they are already loaded, only the way to do this - is to use special extensions like `runkit` or similar. On the userland side there aren't any ways to change them. So, tests should use mocking/stubbing techniques to test such classes from the userland side.
