### ISSUE TITLE
Update dependency GoAOP to have PHP5.6/PHP7 features support

### ISSUE THREAD

**Issue by zuozp8** [Codeception/AspectMock#92]
Currently there are errors when doubling code that contains new language features that cannot be parsed by old GoAOP. GoAOP with version 1.0.x supports new language features (but breaks backwards compatybility as it requires php>=5.6).

**Comment by lisachenko** [comment]
Version 1.0.x of `goaop/framework` works with PHP=5.5 and *CAN* run some 5.6 code (without variadics and splat operators). This version relies on outdated package [andrewsville/php-token-reflection](https://packagist.org/packages/andrewsville/php-token-reflection), so no support for PHP5.6 and 7.0 features.

Master branch (aka 2.x-dev) works with PHP>=5.6 and has a support for PHP7 features because reflection engine was changed to the [goaop/parser-reflection](https://packagist.org/packages/goaop/parser-reflection) component. However, there are no stable 2.x tags right now, if you need something stable for 2.x, then ping me to release a tag.

**Comment by DavertMik** [comment]
I think we are ok to update dependency to GoAOP v 1.0 (not sure why I missed its release, and didn't update earlier) but looks it won't solve your problems for now.

Once GoAOP v2 is out we can switch to it. 

In this case I propose to stick our versions to GoAOP and follow them. So AspectMock 1.0 to work with GoAOP 1.0 and AspectMock 2.0 to work with GoAOP 2.0...

**Comment by DavertMik** [comment]
@lisachenko it seems that GoAOP v2 is really in demand. So could you release it?

**Comment by lisachenko** [comment]
@DavertMik I can release it, but there are things to do and not tested very well. Main change is changing reflection engine to `nikic/PHP-Parser`. Building an AST is more reliable, but requires more time and resources, I'm worrying about fatal errors for xdebug.nested_calls, memory limit, etc. Could you please manually check this fact for big project?

**Comment by zuozp8** [comment]
As GoAOP v2 isn't ready then maybe you could make a branch, set `"goaop/framework": "dev-master"` in composer and perform changes required to work with new GoAOP. I would use such development branch in my project. I'm sure more people need php 5.6/7 support, even if it requires tweaking php settings and reporting bugs here.

**Comment by DavertMik** [comment]
> Could you please manually check this fact for big project?

Sure! But please release something called `alpha`, so I can rely on it and send bugreports.

**Comment by zuozp8** [comment]
bump! GoAOP already released `2.0.0-alpha.1`

**Comment by findli** [comment]
Waiting for update dependencies.

**Comment by DavertMik** [comment]
It's not just like updating a version of Go AOP and  getting it run. It requires some major rewrite of our transformer, so please wait for that.

**Comment by skibish** [comment]
bump! GoAOP released [`2.0.0`](https://github.com/goaop/framework/releases/tag/2.0.0)

**Comment by adrian-enspired** [comment]
@DavertMik any idea how soon GoAOP 2.0 will be integrated?  we want php 7  : )

**Comment by DavertMik** [comment]
Done in master. 2.0 to be released in next hour
